In [1]:
%cd "/Volumes/passport/Present/Work/SpaceLabWork/north_pole/NP_EKM0_TBS0_KP"

/Volumes/passport/Present/Work/SpaceLabWork/north_pole/NP_EKM0_TBS0_KP

Columns are as follows:
out
-+ hydraulic head before evaporation: m, relative to geoid
- hydraulic head after evaporation: m, relative to geoid
+ elevation: m, relative to geoid

/1.1e7

in
precipitation: m/s, lake surface only
x aquifer recharge: m/s, bare surface only, function of P and E
evaporation: m/s, lake surface only
runoff: m/s, only output as discharge to lakes, function of P and E
subsurface flow: m/s # look into it negatve in lakes

In [2]:
import nctoolkit as nc
import os
import numpy as np
import xarray as xr
import proplot as plot 
import matplotlib.pyplot as plt
import pandas as pd
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import matplotlib.path as mpath
import astropy.nddata
import scipy.signal
import math as mth

Please install CDO version 1.9.4 or above: https://code.mpimet.mpg.de/projects/cdo/ or https://anaconda.org/conda-forge/cdo
Please install CDO version 1.9.4 or above: https://code.mpimet.mpg.de/projects/cdo/ or https://anaconda.org/conda-forge/cdo

In [3]:
imax=int(257)
jmax=int(257)
resy=90.0/jmax
resx=90.0/imax
b=(jmax+1)/2
a=(imax+1)/2
lat=np.zeros((257,257))
lon=np.zeros((257,257))

#THIS IS THE WORKING ONE
for i in range(imax) :
    for j in range(jmax):
        dd=np.sqrt((resx*(i-a))**2 + (resy*(j-b))**2) 
        latI=90-dd
        lat[i,j]= latI
        #print("this is "+ str(latI))
        if dd>0 :
            if j>= b:
                lonI=mth.acos((i-a)*resx/dd)*180/mth.pi
                lon[i,j]= lonI
                #print('lon is '+ str(lonI))
            else:
                lonI= 360-mth.acos((i-a)*resx/dd)*180/mth.pi
                lon[i,j]= lonI
                #print('lon is '+ str(lonI))

xglb= int(360/5)
yglb=int(180/5)
#tglb=84
lake_xglb= 0
lake_yglb= 0
lake_tglb= 0
long=np.zeros((xglb,yglb))
latg=np.zeros((xglb,yglb))
dist= np.zeros((257,257))
lakeg= np.zeros((xglb,yglb))#,tglb))
#for south pole multiply lat by (-1) (just lat)

for i in range(xglb):
    long[i,1:yglb]=(i)*5.0

for j in range(yglb):
    latg[1:xglb,j]=(j)*5.0-90
    
for i in range(xglb):
    for j in range(yglb):
        if latg[i,j] >= 45: #less than -45 for sp
            dist=np.sqrt((lat-latg[i,j])**2 + (lon-long[i,j])**2)
            distmin= dist.min()
            distequal = dist==distmin
            lakeg[i,j]= lake1[distequal]

#p=i h=j
for p in range(xglb):
    long[p,1:yglb]=(p)*5.0

for h in range(yglb):
    latg[1:xglb,h]=(h)*5.0-90
    
for p in range(xglb):
    for h in range(yglb):
        if latg[p,h] >= 45: #less than -45 for sp
            dist=np.sqrt((lat-latg[p,h])**2 + (lon-long[p,h])**2)
            distmin= dist.min()
            distequal = dist==distmin
            lakeg[p,h]= lake1[distequal]

In [5]:
#THIS CODE IS THE BEST ONE OF THEM ALL NORTH POLE VERSION



#This code loads in data. It does this by getting it from the directory, then looking at their last 7
#characters, and sorting them. Once it sorts them, it looks for .dat files in the code, and creates a variable
#for each 
#link to code examples here https://newbedev.com/c-python-for-loop-multiple-variables-code-example
#https://newbedev.com/how-to-iterate-over-files-in-a-given-directory
#https://stackoverflow.com/questions/37796598/how-to-sort-file-names-in-a-particular-order-using-python

file_list = os.listdir("/Volumes/passport/Present/Work/SpaceLabWork/north_pole/NP_EKM0_TBS0_KP")

#grab last 4 characters of the file name:
def last_7chars(x):
    return(x[-7:])

#sorted(file_list, key = last_7chars)   

i = 1
xglb= int(360/5)
yglb=int(180/5)
#tglb=84 #I dont think I need it as it will iterate through i
lake_xglb= 0
lake_yglb= 0
lake_tglb= 0
long=np.zeros((xglb,yglb))
latg=np.zeros((xglb,yglb))
dist= np.zeros((257,257))
lakeg= np.zeros((xglb,yglb))
#fortxt=[]
#np.savetxt('//Users//qjf838/Documents/SpaceData/testrun3/northpoletest4.txt', fortxt,delimiter=',')
#np.set_printoptions(threshold=np.inf)
#for south pole multiply lat by (-1) (just lat)


for filename in sorted(file_list, key = last_7chars):
    if filename.endswith(".dat"): # or filename.endswith(".png"):
        globals()["data" + str(i)]= pd.read_csv( filename, sep=' ', header=None, skipinitialspace=True, engine='python')
        a= np.array(globals()["data" + str(i)])
        j=0
        while j <= 7:
            globals()["data" + str(i)+ 'index_' + str(j)] = np.reshape(a[:,j], (257,257))
            #globals()["decidata" + str(i)+ 'index_' + str(j)]= astropy.nddata.block_reduce(globals()["data" + str(i)+ 'index_' + str(j)],block_size=(13,13))
            j+= 1
            
        globals()['lake'+ str(i)]=(data1index_1>data1index_2)*1    
        #globals()['lake'+ str(i)]=(globals()["data" + str(i)+ 'index_' + str(1)]>globals()["data" + str(i)+ 'index_' + str(2)])*1
        #p=i h=j
        for p in range(xglb):
            long[p,1:yglb]=(p)*5.0

        for h in range(yglb):
            latg[1:xglb,h]=(h)*5.0-90

        for p in range(xglb):
            for h in range(yglb):
                if latg[p,h] >= 45: #less than -45 for sp
                    dist=np.sqrt((lat-latg[p,h])**2 + (lon-long[p,h])**2)
                    distmin= dist.min()
                    distequal = dist==distmin
                    #latr= lat> latg[p,h] and/& lat<latg[p+1,h] and lon 
                    lakeg[p,h]= globals()['lake'+ str(i)][distequal]
                    #decilakeg= astropy.nddata.block_reduce(lakeg,block_size=(13,13))

        #file_object = open('//Users//qjf838/Documents/SpaceData/testrun3/northpoletest4.txt', 'a')
        
        #file_object.write(str(lakeg))


        ##file_object.close()
        
        #np.savetxt('//Users//qjf838/Documents/SpaceData/testrun3/data'+str(i)+'.txt', lakeg, delimiter=',')

        #fig = plt.figure()
        #ax = fig.add_subplot(111)  #cmap=lisbon is nice
        #ax.imshow(lakeg, aspect='auto')#, interpolation='nearest')
        #fig.savefig('//Users//qjf838/Documents/SpaceData/testrun/plot'+str(i)+'.png')

        i += 1
    else:
        continue

In [114]:
#This code combines all the previous txt files into one major file. 


forfile=[]
time=84
for i in range(84):
    filename= '//Users//qjf838/Documents/SpaceData/testrun3/data'+str(i+1)+'.txt'
    forfile.append(filename)
    

#filenames = ['file1.txt', 'file2.txt', ...]
with open('/Users/qjf838/Documents/SpaceData/testrun4/testresults.txt', 'w') as outfile:
    for fname in forfile:
        with open(fname) as infile:
            for line in infile:
                outfile.write(line +' ')

In [125]:
f= pd.read_csv('/Users/qjf838/Documents/SpaceData/testrun4/testresults.txt', header=None)

In [171]:
f

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6043,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
6044,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6045,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
6046,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
6047,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [ ]:
#pick 72 combine 36 colums
#[] make longitude first 
#[] add header 72 36 84
#[] outflow/flux value and